# Generated by Django 3.1.2 on 2020-11-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone_num', models.CharField(max_length=11)),
                ('cmnt', models.CharField(max_length=111)),
                ('rd_time', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created', '-rd_time'),
            },
        ),
    ]
