# Generated by Django 3.1.2 on 2020-11-02 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=11)),
                ('cin', models.CharField(max_length=11, unique=True)),
                ('genre_visite', models.CharField(max_length=500)),
                ('montant_a_payer', models.PositiveIntegerField()),
                ('montant_paye', models.PositiveIntegerField(default=0)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.CharField(blank=True, max_length=500)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_completed', models.CharField(default='Not completed', max_length=50)),
                ('adminn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_debut',),
            },
        ),
    ]
